[package]
name = "links_html"
version = "0.1.0"
edition = "2021"
description = "scrape links from html 🧬"
repository = "https://github.com/redcloudvg/links"
documentation = "https://docs.rs/links"
readme = "../README.md"
license-file = "../LICENSE"

[dependencies]
xmlparser = "0.13.6"
